In [43]:
import os
import re
import pandas as pd
import numpy as np

path = '/Users/casadei/experiments/data'

In [23]:
files = os.listdir(path)

In [70]:
def read_all():
    
    datasets = {}
    for file in files:
        current = re.sub('-(train|test)-.*', '', file)
        if not current in datasets:
            datasets[current] = {'train': [], 'test': []}

        mode = 'train' if 'train' in file else 'test'
        content = pd.read_csv(path + '/' + file, header=None)
        datasets[current][mode].append([content.shape[0], content.shape[1] -1])
        
    return datasets
    
def summarize(datasets):
    summary = []
    for dataset in datasets:
        current = [dataset]
        
        for mode in ['train', 'test']:
            if len(datasets[dataset][mode]) > 0:
                instances = np.median(list(zip(*datasets[dataset][mode]))[0])
                features = np.median(list(zip(*datasets[dataset][mode]))[1])
            else:
                instances = 0
                features = 0
            
            current.append(instances)
            current.append(features)
            
        summary.append(np.array(current))
    
    return np.array(summary)

In [78]:
summary = summarize(read_all())
df = pd.DataFrame(data=summary, columns = ('Dataset', 'Train instances', 'Train features', 'Test instances', 'Test features'))
df.sort_values(by=['Dataset'])

,Dataset,Train instances,Train features,Test instances,Test features
29,airfoil,1202.4,5.0,300.6,5.0
4,ccn,1595.2,122.0,398.8,122.0
15,ccun,1595.2,124.0,398.8,124.0
13,concrete,824.0,8.0,206.0,8.0
9,energyCooling,614.4,8.0,153.6,8.0
34,energyHeating,614.4,8.0,153.6,8.0
22,f1,101.0,1.0,0,0
8,f2,241.0,1.0,0,0
30,f3,101.0,1.0,0,0
23,f4,101.0,1.0,0,0
0,f5,101.0,1.0,0,0
16,f6,101.0,1.0,0,0
26,f7,151.0,1.0,0,0
1,keijzer-1,21.0,1.0,2001.0,1.0
24,keijzer-2,41.0,1.0,4001.0,1.0
11,keijzer-3,61.0,1.0,6001.0,1.0
7,keijzer-4,101.0,1.0,101.0,1.0
32,keijzer-5,1000.0,3.0,10000.0,3.0
17,keijzer-6,50.0,1.0,120.0,1.0
10,keijzer-7,100.0,1.0,991.0,1.0
6,keijzer-8,101.0,1.0,1001.0,1.0
31,keijzer-9,101.0,1.0,1001.0,1.0
2,ksinc-0.dat,0,0,100.0,1.0
25,parkinsons,4700.0,18.0,1175.0,18.0
28,ppb,104.8,626.0,26.2,626.0
18,ppb-wth0s,104.8,584.0,26.2,584.0
33,towerData,3999.2,25.0,999.8,25.0
14,vladislavleva-1,100.0,2.0,2025.0,2.0
21,vladislavleva-2,100.0,1.0,221.0,1.0
3,vladislavleva-3,600.0,2.0,5083.0,2.0
20,vladislavleva-4,1024.0,5.0,5000.0,5.0
12,vladislavleva-5,300.0,3.0,2700.0,3.0
19,vladislavleva-7,300.0,2.0,1000.0,2.0
35,vladislavleva-8,50.0,2.0,1089.0,2.0
36,wineRed,1279.2,11.0,319.8,11.0
27,wineWhite,3918.4,11.0,979.6,11.0
5,yacht,246.4,6.0,61.6,6.0

In [80]:
selected = ['airfoil', 'ccn', 'concrete', 'keijzer-7', 'parkinsons', 'ppb', 
            'towerData', 'vladislavleva-1', 'vladislavleva-4', 'yacht']